-- One row per tenant ("team" in the demo's own language — db.settings.teamName).
-- Every other table hangs off org_id so one Supabase project can host many
-- separate teams' data, each fully isolated (RLS policies land in a later stage).
create table orgs (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at before update on orgs
  for each row execute function set_updated_at();
