-- core/session.js members: the people who sign in. auth_user_id links a row
-- to Supabase Auth (supabase.auth.users) once real authentication replaces
-- the demo's local sha256 password hashing (session.js sha256/hashPassword) —
-- nullable because members created by an invite (ADM.users, acceptInvite)
-- may not have accepted / created their Supabase Auth account yet.
create table members (
  id              bigint generated by default as identity primary key,
  org_id          bigint not null references orgs(id) on delete cascade,
  auth_user_id    uuid unique,
  first           text not null default '',
  last            text not null default '',
  email           text not null,
  role_id         text not null,
  active          boolean not null default true,
  must_change_pw  boolean not null default false,
  last_login      timestamptz,
  deactivated_at  timestamptz,
  created_by      bigint references members(id),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (org_id, email),
  foreign key (org_id, role_id) references roles(org_id, id)
);

create trigger set_updated_at before update on members
  for each row execute function set_updated_at();

create index members_org_role_idx on members(org_id, role_id);
create index members_org_active_idx on members(org_id, active);
