-- data/upgrade.js seeds one team per org on first load ("Alpha Prospecting
-- Team"); views/admin.js (teamDlg, teamLogoPick, archiveTeam/restoreTeam)
-- lets managers create more, rename them, set a logo/color, and archive them.
create table teams (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null references orgs(id) on delete cascade,
  name        text not null,
  description text not null default '',
  color       text not null default '#2F6FEB',
  logo_url    text,
  manager_id  bigint references members(id),
  archived    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create trigger set_updated_at before update on teams
  for each row execute function set_updated_at();

create index teams_org_archived_idx on teams(org_id, archived);

-- Current roster (db.teams[].memberIds). Who was on a team and when is
-- team_history below; this table is just "who is on it right now".
create table team_members (
  org_id     bigint not null references orgs(id) on delete cascade,
  team_id    bigint not null references teams(id) on delete cascade,
  member_id  bigint not null references members(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (team_id, member_id)
);

create trigger set_updated_at before update on team_members
  for each row execute function set_updated_at();

create index team_members_member_idx on team_members(org_id, member_id);

-- Join/leave log. The demo declares `db.teamHistory` (upgradeDb) as the
-- record of moves between teams over time, distinct from the current roster.
create table team_history (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  team_id    bigint not null references teams(id) on delete cascade,
  member_id  bigint not null references members(id) on delete cascade,
  joined     timestamptz not null default now(),
  "left"     timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at before update on team_history
  for each row execute function set_updated_at();

create index team_history_member_idx on team_history(org_id, member_id);
create index team_history_team_idx on team_history(org_id, team_id);

-- db.teams[].listIds / db.teams[].campaignIds: which lists and campaigns a
-- team owns, used by teamPerf() and the lists/campaigns admin screens.
create table team_lists (
  org_id     bigint not null references orgs(id) on delete cascade,
  team_id    bigint not null references teams(id) on delete cascade,
  list_id    bigint not null,  -- FK added in 0006_lists.sql once lists exists
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (team_id, list_id)
);

create trigger set_updated_at before update on team_lists
  for each row execute function set_updated_at();

create table team_campaigns (
  org_id      bigint not null references orgs(id) on delete cascade,
  team_id     bigint not null references teams(id) on delete cascade,
  campaign_id bigint not null,  -- FK added in 0011_campaigns_and_templates.sql
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (team_id, campaign_id)
);

create trigger set_updated_at before update on team_campaigns
  for each row execute function set_updated_at();

-- db.members[].listIds: a member's own list subscriptions (independent of
-- team_lists — a member can see a list without their team owning it).
create table member_lists (
  org_id     bigint not null references orgs(id) on delete cascade,
  member_id  bigint not null references members(id) on delete cascade,
  list_id    bigint not null,  -- FK added in 0006_lists.sql once lists exists
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (member_id, list_id)
);

create trigger set_updated_at before update on member_lists
  for each row execute function set_updated_at();
