-- Prospecting lists (db.lists: {id, name, archived, createdAt}).
create table lists (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  name       text not null,
  archived   boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at before update on lists
  for each row execute function set_updated_at();

create index lists_org_archived_idx on lists(org_id, archived);

-- Back-fill the FKs left dangling in 0005_teams.sql now that lists exists.
alter table team_lists
  add constraint team_lists_list_fk foreign key (list_id) references lists(id) on delete cascade;
alter table member_lists
  add constraint member_lists_list_fk foreign key (list_id) references lists(id) on delete cascade;
