-- core/statuses.js defaultStatuses(): the lead-status pipeline shown as
-- colored badges (badge() in features/activity.js). Teams can rename, add,
-- reorder or deactivate statuses in Settings (statusForm/moveStatus/
-- deleteStatus in views/settings.js), but 5 of the 7 defaults are "locked"
-- (can't be deleted, only renamed) because the app's own logic sets a lead's
-- status to one of those keys directly (logActivity, setDnc).
create table statuses (
  org_id     bigint not null references orgs(id) on delete cascade,
  key        text not null,
  label      text not null,
  tone       text not null default '',
  active     boolean not null default true,
  locked     boolean not null default false,
  "order"    integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (org_id, key)
);

create trigger set_updated_at before update on statuses
  for each row execute function set_updated_at();

-- data/seed.js outcomes: what happened on a call/text (activityForm in
-- features/activity.js). conv/appt/dnc each drive a side effect in
-- logActivity() — conv advances status to "contacted", appt to
-- "appointment", dnc sets the DNC flag and status to "do_not_call".
create table outcomes (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  name       text not null,
  conv       boolean not null default false,
  appt       boolean not null default false,
  dnc        boolean not null default false,
  disabled   boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, name)
);

create trigger set_updated_at before update on outcomes
  for each row execute function set_updated_at();

create index outcomes_org_disabled_idx on outcomes(org_id, disabled);
