-- core/fields.js: teams add their own merge fields (Settings → Fields).
-- `type` is one of CF_TYPES (text, long_text, number, money, date, yes_no,
-- choice); `choices` only has values when type='choice'. inTable/onCard
-- control whether the field shows as a leads-table column (resolvedColumns)
-- or a CRM card field (cardFieldsFor); `order` controls display order
-- (keyFromLabel/keyProblem enforce the key format and uniqueness).
create table custom_fields (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  key        text not null,
  label      text not null,
  type       text not null,
  choices    jsonb not null default '[]'::jsonb,
  hint       text not null default '',
  in_table   boolean not null default false,
  on_card    boolean not null default false,
  active     boolean not null default true,
  "order"    integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, key),
  check (type in ('text','long_text','number','money','date','yes_no','choice'))
);

create trigger set_updated_at before update on custom_fields
  for each row execute function set_updated_at();

create index custom_fields_org_active_idx on custom_fields(org_id, active);

-- defaultBuiltInFields(): the 8 fields that ship with every team (first,
-- last, phone, email, addr, city, state, zip). `always` marks the 3 that
-- can be hidden from the table but never turned fully off (first/last/phone
-- — see fieldTypeChanged / toggleField in views/settings.js).
create table built_in_fields (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  key        text not null,
  label      text not null,
  visible    boolean not null default true,
  required   boolean not null default false,
  always     boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, key)
);

create trigger set_updated_at before update on built_in_fields
  for each row execute function set_updated_at();
