-- features/leads.js / features/activity.js: the core record. assigned_id is
-- nullable (an imported lead can land unassigned — importRun leaves
-- `assigned: s.assignee?+s.assignee:null`). status_key points at the team's
-- own statuses row, not a fixed enum, since teams can add statuses.
-- dnc/dnt/dncontact are the three independent do-not flags blockMsg()/
-- isBlocked() read (Do Not Call, Do Not Text, Do Not Contact-at-all).
-- import_id is nullable — most leads are hand-entered, not imported; its FK
-- is added in 0012_imports.sql once the imports table exists.
create table leads (
  id           bigint generated by default as identity primary key,
  org_id       bigint not null references orgs(id) on delete cascade,
  first        text not null default '',
  last         text not null default '',
  email        text not null default '',
  addr         text not null default '',
  city         text not null default '',
  state        text not null default '',
  zip          text not null default '',
  assigned_id  bigint references members(id),
  status_key   text not null default 'new',
  dnc          boolean not null default false,
  dnt          boolean not null default false,
  dncontact    boolean not null default false,
  archived     boolean not null default false,
  source       text not null default 'manual',
  import_id    bigint,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  foreign key (org_id, status_key) references statuses(org_id, key)
);

create trigger set_updated_at before update on leads
  for each row execute function set_updated_at();

-- filteredLeads()'s own filters, one index per column it narrows by.
create index leads_org_archived_idx    on leads(org_id, archived);
create index leads_org_assigned_idx    on leads(org_id, assigned_id);
create index leads_org_status_idx      on leads(org_id, status_key);
create index leads_org_dnc_idx         on leads(org_id, dnc);
create index leads_org_dnt_idx         on leads(org_id, dnt);
create index leads_org_dncontact_idx   on leads(org_id, dncontact);
create index leads_org_source_idx      on leads(org_id, source);
create index leads_org_city_idx        on leads(org_id, city);
create index leads_org_zip_idx         on leads(org_id, zip);
create index leads_org_created_idx     on leads(org_id, created_at);
-- state.q free-text search (full name + addr + city + zip + email, filteredLeads()).
create index leads_search_trgm_idx on leads
  using gin ((coalesce(first,'') || ' ' || coalesce(last,'') || ' ' || coalesce(addr,'') || ' ' || coalesce(city,'') || ' ' || coalesce(zip,'') || ' ' || coalesce(email,'')) gin_trgm_ops);

-- lead.phones[]: each lead can have several numbers (mobile/home/work/other).
-- `position` is the phones[] array index — position 0 is what pretty(),
-- callBtn() and the workspace queue treat as "the" number by default.
create table lead_phones (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  lead_id    bigint not null references leads(id) on delete cascade,
  n          text not null,
  type       text not null default 'mobile',
  "position" integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lead_id, n),
  check (type in ('mobile','home','work','other'))
);

create trigger set_updated_at before update on lead_phones
  for each row execute function set_updated_at();

create index lead_phones_lead_idx on lead_phones(org_id, lead_id);

-- lead.listIds[]: which prospecting lists a lead sits on (many-to-many).
create table lead_lists (
  org_id     bigint not null references orgs(id) on delete cascade,
  lead_id    bigint not null references leads(id) on delete cascade,
  list_id    bigint not null references lists(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (lead_id, list_id)
);

create trigger set_updated_at before update on lead_lists
  for each row execute function set_updated_at();

create index lead_lists_list_idx on lead_lists(org_id, list_id);

-- lead.custom{}: one row per (lead, custom field) that actually has a value
-- — cfClean()/setCustom() never store empty values, matching the demo's
-- sparse `lead.custom` object (only fields the lead actually has are keys).
create table lead_custom_values (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  lead_id    bigint not null references leads(id) on delete cascade,
  field_key  text not null,
  value      jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lead_id, field_key),
  foreign key (org_id, field_key) references custom_fields(org_id, key) on delete cascade
);

create trigger set_updated_at before update on lead_custom_values
  for each row execute function set_updated_at();

create index lead_custom_values_field_idx on lead_custom_values(org_id, field_key);
