-- features/activity.js logActivity(): every call/text/reply/door-knock.
-- outcome_id is required — logActivity() always resolves and stores one.
-- list_id/campaign_id record which list or campaign the attempt happened
-- under (used by reports and the campaign detail view); both optional.
-- phone is the raw number dialed/texted, stored as text (not an FK to
-- lead_phones) since the demo itself just carries the string through.
create table activities (
  id            bigint generated by default as identity primary key,
  org_id        bigint not null references orgs(id) on delete cascade,
  lead_id       bigint not null references leads(id) on delete cascade,
  type          text not null,
  outcome_id    bigint not null references outcomes(id),
  user_id       bigint not null references members(id),
  at            timestamptz not null default now(),
  note          text not null default '',
  list_id       bigint references lists(id),
  campaign_id   bigint,  -- FK added in 0011_campaigns_and_templates.sql
  duration_min  integer,
  phone         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  check (type in ('call','text','reply','door_knock'))
);

create trigger set_updated_at before update on activities
  for each row execute function set_updated_at();

-- leadActs()/lastAct(): most-recent-first per lead.
create index activities_lead_at_idx on activities(lead_id, at desc);
-- stats()/pace(): filtered by user + date range, or just date range for the team.
create index activities_org_user_at_idx on activities(org_id, user_id, at);
create index activities_org_type_at_idx on activities(org_id, type, at);
create index activities_org_campaign_idx on activities(org_id, campaign_id);

-- features/activity.js follow-ups: one pending follow-up replaces the last
-- (logActivity cancels the old one), or fuDone/fuCancel/fuSnooze/
-- fuReschedule change status. assignee_id defaults to the lead's own
-- assignment but can differ (reassign() keeps pending follow-ups in sync,
-- but done/cancelled ones keep their original assignee for history).
create table follow_ups (
  id            bigint generated by default as identity primary key,
  org_id        bigint not null references orgs(id) on delete cascade,
  lead_id       bigint not null references leads(id) on delete cascade,
  due           date not null,
  status        text not null default 'pending',
  note          text not null default '',
  assignee_id   bigint references members(id),
  cancel_reason text,
  cancelled_by  bigint references members(id),
  done_at       timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  check (status in ('pending','done','cancelled'))
);

create trigger set_updated_at before update on follow_ups
  for each row execute function set_updated_at();

-- views/followups.js: "mine" = assignee + status, sorted by due; nextFu()
-- (features/activity.js) = one pending follow-up per lead, soonest due.
create index follow_ups_lead_status_idx on follow_ups(lead_id, status);
create index follow_ups_assignee_status_due_idx on follow_ups(assignee_id, status, due);
create index follow_ups_org_status_due_idx on follow_ups(org_id, status, due);

-- features/activity.js addNote(): quick notes anyone can add, manager-only
-- notes gated by the managerNotes permission (kind = 'quick' | 'manager').
create table notes (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  lead_id    bigint not null references leads(id) on delete cascade,
  user_id    bigint not null references members(id),
  at         timestamptz not null default now(),
  text       text not null,
  kind       text not null default 'quick',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (kind in ('quick','manager'))
);

create trigger set_updated_at before update on notes
  for each row execute function set_updated_at();

create index notes_lead_idx on notes(lead_id, at desc);
