-- views/campaigns.js templateForm(): reusable message bodies with
-- {{merge_field}} placeholders (renderTpl() in features/activity.js).
create table templates (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  name       text not null,
  style      text not null default 'standard',
  body       text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at before update on templates
  for each row execute function set_updated_at();

-- views/campaigns.js campaignForm()/duplicateCampaign(): a named outreach
-- push with its own body (independent copy, not a live link to a template —
-- duplicateCampaign() copies `body` by value, hence duplicated_from just
-- records provenance, not a live foreign key to re-render from).
create table campaigns (
  id               bigint generated by default as identity primary key,
  org_id           bigint not null references orgs(id) on delete cascade,
  name             text not null,
  type             text not null default 'custom',
  body             text not null,
  archived         boolean not null default false,
  duplicated_from  bigint references campaigns(id),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create trigger set_updated_at before update on campaigns
  for each row execute function set_updated_at();

create index campaigns_org_archived_idx on campaigns(org_id, archived);

-- features/leads.js addLeadsToCampaign(): one card per (campaign, lead) —
-- the per-lead send status (draft/ready/sent/replied), never duplicated.
create table campaign_leads (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null references orgs(id) on delete cascade,
  campaign_id bigint not null references campaigns(id) on delete cascade,
  lead_id     bigint not null references leads(id) on delete cascade,
  body        text,
  status      text not null default 'draft',
  sent_at     timestamptz,
  sent_by     bigint references members(id),
  replied_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (campaign_id, lead_id),
  check (status in ('draft','ready','sent','replied'))
);

create trigger set_updated_at before update on campaign_leads
  for each row execute function set_updated_at();

create index campaign_leads_lead_idx on campaign_leads(org_id, lead_id);
create index campaign_leads_status_idx on campaign_leads(org_id, campaign_id, status);

-- Back-fill the FKs left dangling until campaigns existed.
alter table activities
  add constraint activities_campaign_fk foreign key (campaign_id) references campaigns(id);
alter table team_campaigns
  add constraint team_campaigns_campaign_fk foreign key (campaign_id) references campaigns(id) on delete cascade;
