-- views/imports.js importRun(): one row per uploaded file, whether or not
-- it created a list on the fly. by_id is who ran the import; status moves
-- completed → undone (undoImport()).
create table imports (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  file       text not null,
  list_id    bigint references lists(id),
  rows       integer not null default 0,
  imported   integer not null default 0,
  dups       integer not null default 0,
  status     text not null default 'running',
  by_id      bigint references members(id),
  at         timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('running','completed','undone'))
);

create trigger set_updated_at before update on imports
  for each row execute function set_updated_at();

-- job.leadIds[]: which leads this import created, so undoImport() can
-- remove the ones nobody has worked yet (leads with logged activity are
-- kept — see the check in undoImport()'s confirm dialog).
create table import_leads (
  org_id     bigint not null references orgs(id) on delete cascade,
  import_id  bigint not null references imports(id) on delete cascade,
  lead_id    bigint not null references leads(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (import_id, lead_id)
);

create trigger set_updated_at before update on import_leads
  for each row execute function set_updated_at();

create index import_leads_lead_idx on import_leads(org_id, lead_id);

-- Back-fill leads.import_id now that imports exists (0009_leads.sql).
alter table leads
  add constraint leads_import_fk foreign key (import_id) references imports(id);
create index leads_org_import_idx on leads(org_id, import_id);
