-- features/crm.js: a pipeline is a named board (e.g. "Seller Leads",
-- "Probate" — `kind` is a free label, not an enum, matching newPipeline()).
create table pipelines (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  name       text not null,
  kind       text not null default 'seller',
  archived   boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at before update on pipelines
  for each row execute function set_updated_at();

create index pipelines_org_archived_idx on pipelines(org_id, archived);

-- defaultStages(): 14 stages ship with every new pipeline (New Lead through
-- Closed/Lost Lead). `kind` is 'active' | 'closed' | 'lost' — drives the
-- CRM dashboard's win-rate math (closed ÷ (closed + lost), views/crmdash.js).
-- `prob` is the stage's win probability (0–100), used by dealMath()'s
-- weighted-forecast calculation. `position` is display order in the board
-- and is what moveStage()/stageMenu() reorder.
create table stages (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null references orgs(id) on delete cascade,
  pipeline_id bigint not null references pipelines(id) on delete cascade,
  name        text not null,
  prob        integer not null default 0,
  kind        text not null default 'active',
  color       text not null default '#8E8E93',
  archived    boolean not null default false,
  "position"  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  check (kind in ('active','closed','lost')),
  check (prob between 0 and 100)
);

create trigger set_updated_at before update on stages
  for each row execute function set_updated_at();

create index stages_pipeline_idx on stages(org_id, pipeline_id, "position");

-- features/crm.js addToCrm()/dealMath(): the CRM record for a lead — same
-- lead, no copy, one deal per (lead, pipeline) so a lead can be in more than
-- one pipeline (e.g. Seller Leads and Probate) but never duplicated within
-- one. Financial columns feed dealMath()'s gross → net → weighted chain
-- exactly as commented there: gross = price × comm_pct, minus referral,
-- minus brokerage split/fee, minus closing costs = net, then net is split
-- team_split_pct / (100 − team_split_pct) between team and agent.
create table deals (
  id                bigint generated by default as identity primary key,
  org_id            bigint not null references orgs(id) on delete cascade,
  lead_id           bigint not null references leads(id) on delete cascade,
  pipeline_id       bigint not null references pipelines(id) on delete cascade,
  stage_id          bigint not null references stages(id),
  assigned_id       bigint references members(id),
  temperature       text not null default 'warm',
  price             numeric(14,2) not null default 0,
  comm_pct          numeric(5,2) not null default 0,
  referral_pct      numeric(5,2) not null default 0,
  team_split_pct    numeric(5,2) not null default 0,
  brokerage_pct     numeric(5,2) not null default 0,
  brokerage_fee     numeric(14,2) not null default 0,
  closing_costs     numeric(14,2) not null default 0,
  close_date        date,
  next_fu           date,
  notes             text not null default '',
  stage_entered_at  timestamptz not null default now(),
  created_by        bigint references members(id),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (lead_id, pipeline_id),
  check (temperature in ('hot','warm','cold'))
);

create trigger set_updated_at before update on deals
  for each row execute function set_updated_at();

-- crmDeals()'s own filters (pipeline + stage + agent + temperature always;
-- follow-up/price/close-date ranges are the "more filters" panel).
create index deals_org_pipeline_idx on deals(org_id, pipeline_id);
create index deals_pipeline_stage_idx on deals(pipeline_id, stage_id);
create index deals_org_assigned_idx on deals(org_id, assigned_id);
create index deals_org_temperature_idx on deals(org_id, temperature);
create index deals_org_next_fu_idx on deals(org_id, next_fu);
create index deals_org_close_date_idx on deals(org_id, close_date);
create index deals_org_price_idx on deals(org_id, price);

-- dealLog(): every stage move / edit, newest first (deal.history.unshift).
create table deal_history (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  deal_id    bigint not null references deals(id) on delete cascade,
  at         timestamptz not null default now(),
  user_id    bigint references members(id),
  type       text not null,
  detail     text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at before update on deal_history
  for each row execute function set_updated_at();

create index deal_history_deal_at_idx on deal_history(deal_id, at desc);
