-- db.settings: one row per org. table_columns/card_fields are ordered lists
-- of column/field ids (resolvedColumns()/cardFieldsFor() in core/fields.js),
-- so they stay jsonb arrays rather than a join table — order is part of the
-- value. pts_* and weekly_goal feed stats()'s points formula and pace();
-- working_days is the array of weekday numbers (1=Mon..7=Sun) pace() walks.
-- import_cfg is the whole "Imports" settings tab (phone/email slot counts,
-- dedupe rules, required fields, default assignment) as one jsonb blob,
-- matching how the demo already treats it as a single opaque settings object.
create table org_settings (
  org_id         bigint primary key references orgs(id) on delete cascade,
  team_name      text not null default '',
  agent_name     text not null default '',
  table_columns  jsonb not null default '[]'::jsonb,
  card_fields    jsonb not null default '[]'::jsonb,
  pts_call       numeric(6,2) not null default 1,
  pts_text       numeric(6,2) not null default 1,
  pts_door       numeric(6,2) not null default 2,
  pts_conv       numeric(6,2) not null default 5,
  pts_appt       numeric(6,2) not null default 25,
  weekly_goal    integer not null default 250,
  working_days   jsonb not null default '[1,2,3,4,5]'::jsonb,
  import_cfg     jsonb not null default '{}'::jsonb,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create trigger set_updated_at before update on org_settings
  for each row execute function set_updated_at();

-- core/session.js audit(): a running log of who did what (views/audit.js).
-- table_name is free text (it names a table conceptually — "leads",
-- "deals", "campaign_leads" — but audit rows must survive even if the
-- referenced row is later deleted, so it is not a real FK).
create table audit_log (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references orgs(id) on delete cascade,
  at         timestamptz not null default now(),
  user_id    bigint references members(id),
  action     text not null,
  table_name text not null,
  detail     text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at before update on audit_log
  for each row execute function set_updated_at();

create index audit_log_org_at_idx on audit_log(org_id, at desc);
create index audit_log_org_table_idx on audit_log(org_id, table_name);
