import { field, listOpts, memberOpts, opts } from '../core/dialog.js';
import { activeFields } from '../core/fields.js';
import { can } from '../core/permissions.js';
import { memberName } from '../core/session.js';
import { V, state } from '../core/state.js';
import { esc, fmtDT, pretty } from '../core/util.js';
import { db } from '../data/persist.js';
import { badge, full } from '../features/activity.js';
import { downloadSample, importCheck, importRun, undoImport } from '../features/imports.js';

V.imports = () => {
  if(!can("import")) return '<div class="card empty">Importing is turned off for your role. Ask an owner to switch it on in Settings → Team &amp; permissions.</div>';
  const st = state.importStep;
  if(st) return importWizard();
  return `<div class="page-head"><div><h2>Imports</h2><p>Bulk-upload leads from Excel (.xlsx) or CSV</p></div></div>
  <div class="card" style="text-align:center;padding:40px;border:2px dashed var(--border)" ondragover="event.preventDefault()" ondrop="event.preventDefault();handleFile(event.dataTransfer.files[0])"><div style="font-size:40px">⇪</div><b>Drop an Excel or CSV file here</b><div class="muted small" style="margin:6px 0 14px">First row must be column headers. You'll match the columns to fields next. Duplicates are matched on ${[db.settings.importCfg.dupPhone&&"phone",db.settings.importCfg.dupEmail&&"email",db.settings.importCfg.dupAddress&&"address + ZIP"].filter(Boolean).join(", ")||"nothing"}.</div><div class="actions" style="justify-content:center"><button class="btn" onclick="document.getElementById('fileIn').click()">Choose file</button><button class="btn tint" onclick="downloadSample()">Download sample CSV</button></div><p class="small muted" style="margin:14px 0 0">Recognised headers: First Name, Last Name, Phone 1 … Phone ${db.settings.importCfg.phoneSlots}, Email, Address, City, State, ZIP, Notes, Tags — plus your own fields${activeFields().length?" ("+activeFields().map(f=>esc(f.label)).join(", ")+")":""} (any order, any capitalisation).</p></div>
  <h3 style="margin:22px 0 8px;font-size:15px">Import history</h3>
  <div class="card flush"><div class="tbl"><table><thead><tr><th>File</th><th>List</th><th>Rows</th><th>Imported</th><th>Duplicates</th><th>Status</th><th>By</th><th>When</th><th></th></tr></thead><tbody>${db.imports.slice().reverse().map(j=>`<tr><td>${esc(j.file)}</td><td>${esc(db.lists.find(l=>l.id===j.listId)?.name||"—")}</td><td class="mono">${j.rows}</td><td class="mono">${j.imported}</td><td class="mono">${j.dups}</td><td><span class="badge ${j.status==="completed"?"green":j.status==="undone"?"":"orange"}">${j.status}</span></td><td>${esc(memberName(j.by))}</td><td>${fmtDT(j.at)}</td><td>${j.status==="completed"&&j.imported>0?`<button class="btn plain sm" onclick="undoImport(${j.id})">Undo</button>`:""}</td></tr>`).join("")||'<tr><td colspan="9" class="empty">No imports yet.</td></tr>'}</tbody></table></div></div>`;
};
export function importWizard(){
  const s=state.importStep!;
  if(s.step==="map") return `<div class="page-head"><div><a href="#imports" onclick="state.importStep=null;draw();return false">‹ Imports</a><h2>Match columns</h2><p>${esc(s.file)} · ${s.data.length} rows${s.truncated?" (capped at ${(db.settings.importCfg.maxRows).toLocaleString()})":""}</p></div><div class="actions"><button class="btn plain" onclick="state.importStep=null;draw()">Cancel</button><button class="btn" onclick="importCheck()">Next: check duplicates ›</button></div></div>
    <div class="card flush"><div class="tbl"><table><thead><tr><th>Column in your file</th><th>Example</th><th>Import as</th></tr></thead><tbody>${s.headers.map((h,i)=>`<tr><td><b>${esc(h)}</b></td><td class="small muted">${esc(s.data[0]?.[i]??"")}</td><td><select style="max-width:240px" onchange="state.importStep.map[${i}]=this.value">${opts(s.FIELDS,s.map[i])}</select></td></tr>`).join("")}</tbody></table></div></div>
    <div class="card" style="margin-top:16px"><div class="grid g2">${field("Import into list",`<select id="iL">${listOpts(s.listId ?? db.settings.importCfg.defaultList ?? "","Create a new list from the file name")}</select>`)}${field("Assign all leads to",`<select id="iA">${memberOpts(s.assignee ?? db.settings.importCfg.defaultAssign ?? "","Leave unassigned")}</select>`)}</div><p class="small muted" style="margin-top:10px">${db.settings.importCfg.phoneSlots} phone column(s) offered${db.settings.importCfg.flagDnc?' · "DNC" in Tags or Notes marks the lead Do Not Call':""} · duplicates matched on ${[db.settings.importCfg.dupPhone&&"phone",db.settings.importCfg.dupEmail&&"email",db.settings.importCfg.dupAddress&&"address"].filter(Boolean).join(", ")||"nothing"}. Change any of this in <a href="#settings" onclick="state.setTab='import';go('settings');return false">Settings → Import</a>.</p></div>`;
  if(s.step==="check"){
    if(s.loading) return `<div class="page-head"><div><a href="#imports" onclick="state.importStep.step='map';draw();return false">‹ Back</a><h2>Check duplicates</h2><p class="muted">Checking ${s.data.length} rows against your existing leads…</p></div></div>`;
    return `<div class="page-head"><div><a href="#imports" onclick="state.importStep.step='map';draw();return false">‹ Back</a><h2>Check duplicates</h2><p>${s.ready!.length} ready to import · ${s.dups!.length} possible duplicates · ${s.bad!.length} rows without a name or phone (skipped)</p></div><div class="actions"><button class="btn plain" onclick="state.importStep=null;draw()">Cancel</button><button class="btn" onclick="importRun()">Import ${s.ready!.length + s.dups!.filter(d=>d.action==="import").length} leads</button></div></div>
    ${s.dups!.length?`<div class="card flush" style="margin-bottom:16px"><div class="tbl"><table><thead><tr><th>Row in file</th><th>Matches existing lead</th><th>Matched on</th><th>What to do</th></tr></thead><tbody>${s.dups!.map((d,i)=>`<tr><td><b>${esc(d.row.first)} ${esc(d.row.last)}</b><div class="small muted">${pretty(d.row.phones[0])} · ${esc(d.row.addr)}</div></td><td><b>${esc(full(d.match))}</b><div class="small muted">${pretty(d.match.phones![0]?.n)} · ${esc(d.match.addr)} · ${esc(memberName(d.match.assigned))}</div></td><td><span class="badge orange">${d.on}</span></td><td><select style="max-width:260px" onchange="state.importStep.dups[${i}].action=this.value">${opts([["skip","Skip this row"],["merge","Merge into existing (add to list, fill blanks)"],["import","Import as a new lead anyway"]],d.action)}</select></td></tr>`).join("")}</tbody></table></div></div>`:'<div class="alert green" style="margin-bottom:16px">No duplicates found.</div>'}
    <div class="card flush"><div class="tbl"><table><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Address</th><th>City</th><th>ZIP</th>${activeFields().map(f=>`<th>${esc(f.label)}</th>`).join("")}<th>Flags</th></tr></thead><tbody>${s.ready!.slice(0,50).map(r=>`<tr><td>${esc(r.first)} ${esc(r.last)}</td><td class="mono">${r.phones.map(pretty).join(", ")||"—"}</td><td>${esc(r.email)}</td><td>${esc(r.addr)}</td><td>${esc(r.city)}</td><td>${esc(r.zip)}</td>${activeFields().map(f=>`<td>${esc((r.custom||{})[f.key]||"")}</td>`).join("")}<td>${r.dnc?'<span class="badge red">DNC</span>':""}</td></tr>`).join("")}${s.ready!.length>50?`<tr><td colspan="${7+activeFields().length}" class="muted small">…and ${s.ready!.length-50} more</td></tr>`:""}</tbody></table></div></div>`;
  }
  return "";
}

// ---------------------------------------------------------------- reports & scoreboard
