// GATE G6 item 7 — data-integrity certification: commission and forecast
// money for 20 hand-calculated deals match dealMath() to the cent.
//
// Certified facts this suite rests on (verified by reading, 2026-10-01):
//
//  * dealMath()/num()/pct() live in src/features/crm.js lines 31-32 and
//    38-50 and are BYTE-IDENTICAL (modulo the `export ` keyword) to the
//    demo's docs/original-demo.html.ref lines 1480-1481 and 1487-1499 —
//    checked with `diff` on the exact line ranges. money() in
//    src/core/fields.js line 30 is byte-identical to demo line 502.
//
//  * The expectations below were NOT derived with JS floats. They come from
//    tests/certification/money-oracle.py, which hand-transcribes the formula
//    and evaluates it with Python's decimal module at 50 digits (every
//    operation exact). Regenerate with:
//        python3 tests/certification/money-oracle.py
//    and paste its JSON output over the ORACLE literal below. The JS under
//    test is therefore the only IEEE-754 arithmetic in the loop, and the
//    assertion |js - oracle| < 0.005 means "agrees when rounded to cents".
//
//  * SQL side: supabase/migrations/0018_search_deals.sql (lines 110-153)
//    and 0019_stats.sql (deal_money CTE, lines ~177-213) DO recompute the
//    same chain server-side in exact `numeric` arithmetic, with
//    least(100,greatest(0,·)) as pct()'s clamp and greatest(0,·) as the two
//    Math.max clamps — formula order identical. 0018 additionally rounds
//    its returned net/weighted to cents (`round(net_amt,2)`, line 198), but
//    data/repo-supabase.js's mapDealRow() (line 1485) never maps those
//    columns into the client deal: displayed money is ALWAYS recomputed by
//    this JS dealMath() from the raw stored fields, and the SQL values are
//    only used for server-side filtering/sorting. JS<->SQL arithmetic parity
//    itself is already certified by tests/unit/dealmath-parity.test.ts
//    against a real Postgres; this suite certifies the JS against an
//    independent decimal oracle instead, so the two suites brace each other.
//    Column types (0013_crm_pipeline.sql lines 60-66): price/brokerage_fee/
//    closing_costs numeric(14,2), the four *_pct numeric(5,2) — i.e. inputs
//    are rounded to 2 decimals at storage time on the supabase backend.
//
// This file deliberately does NOT repeat the cases of tests/unit/
// dealmath.test.ts (zero/negative/junk/clamp unit cases with hand-traced JS
// floats) — it extends them with the independent-decimal-oracle methodology
// and 20 stress deals, plus money() display-rounding certification.
//
// Import harness: same solved pattern as tests/unit/dealmath.test.ts —
// mock main.js's draw, stub the DOM nodes crm.js's import chain touches,
// resolve data/persist.js first (crm.js <-> persist.js <-> seed.js circular
// import), then import features/crm.js.
import { describe, expect, it, vi } from 'vitest';

vi.mock('../../src/main.js', () => ({ draw: vi.fn() }));

document.body.innerHTML = `<div id="app"></div><div id="toast"></div><input type="file" id="restoreIn"><dialog id="dlg"></dialog>`;

await import('../../src/data/persist.js');
const { dealMath, num, pct }: any = await import('../../src/features/crm.js');
const { money }: any = await import('../../src/core/fields.js');

// ---------------------------------------------------------------- fixture
// Generated by: python3 tests/certification/money-oracle.py  (pasted verbatim)
// inputs order: [price, commPct, referralPct, brokeragePct, brokerageFee, closingCosts, teamSplitPct, prob]
// Money values are exact decimal strings (Python decimal, prec=50).
const ORACLE = [
  {"name": "D01 round numbers 425000 @ 3%", "inputs": ["425000", "3", "0", "0", "0", "0", "0", "80"], "gross": "12750", "referral": "0", "brokerage": "0", "net": "12750", "teamShare": "0", "agentShare": "12750", "weighted": "10200"},
  {"name": "D02 cents price 123456.78 @ 2.75%", "inputs": ["123456.78", "2.75", "0", "20", "0", "500", "50", "55"], "gross": "3395.06145", "referral": "0", "brokerage": "679.01229", "net": "2216.04916", "teamShare": "1108.02458", "agentShare": "1108.02458", "weighted": "1218.827038"},
  {"name": "D03 float-trap chain 100000 @ 2.9%", "inputs": ["100000", "2.9", "10", "15", "299.99", "1234.56", "50", "35"], "gross": "2900", "referral": "290", "brokerage": "691.49", "net": "683.95", "teamShare": "341.975", "agentShare": "341.975", "weighted": "239.3825"},
  {"name": "D04 no referral", "inputs": ["350000", "3", "0", "30", "495", "250", "20", "95"], "gross": "10500", "referral": "0", "brokerage": "3645", "net": "6605", "teamShare": "1321", "agentShare": "5284", "weighted": "6274.75"},
  {"name": "D05 no brokerage", "inputs": ["275000", "2.5", "25", "0", "0", "0", "50", "65"], "gross": "6875", "referral": "1718.75", "brokerage": "0", "net": "5156.25", "teamShare": "2578.125", "agentShare": "2578.125", "weighted": "3351.5625"},
  {"name": "D06 everything zero", "inputs": ["0", "0", "0", "0", "0", "0", "0", "0"], "gross": "0", "referral": "0", "brokerage": "0", "net": "0", "teamShare": "0", "agentShare": "0", "weighted": "0"},
  {"name": "D07 clamp: fee > afterRef -> afterBrok 0", "inputs": ["50000", "1", "0", "0", "2000", "100", "50", "100"], "gross": "500", "referral": "0", "brokerage": "2000", "net": "0", "teamShare": "0", "agentShare": "0", "weighted": "0"},
  {"name": "D08 clamp: closing > afterBrok -> net 0", "inputs": ["100000", "3", "0", "50", "0", "2000", "50", "95"], "gross": "3000", "referral": "0", "brokerage": "1500", "net": "0", "teamShare": "0", "agentShare": "0", "weighted": "0"},
  {"name": "D09 teamSplit 0", "inputs": ["600000", "3", "10", "10", "0", "0", "0", "45"], "gross": "18000", "referral": "1800", "brokerage": "1620", "net": "14580", "teamShare": "0", "agentShare": "14580", "weighted": "6561"},
  {"name": "D10 teamSplit 50", "inputs": ["600000", "3", "10", "10", "0", "0", "50", "45"], "gross": "18000", "referral": "1800", "brokerage": "1620", "net": "14580", "teamShare": "7290", "agentShare": "7290", "weighted": "6561"},
  {"name": "D11 teamSplit 100", "inputs": ["600000", "3", "10", "10", "0", "0", "100", "45"], "gross": "18000", "referral": "1800", "brokerage": "1620", "net": "14580", "teamShare": "14580", "agentShare": "0", "weighted": "6561"},
  {"name": "D12 prob 0", "inputs": ["999999", "3.25", "5", "12.5", "199", "850", "35", "0"], "gross": "32499.9675", "referral": "1624.998375", "brokerage": "4058.371140625", "net": "25966.597984375", "teamShare": "9088.30929453125", "agentShare": "16878.28868984375", "weighted": "0"},
  {"name": "D13 prob 35, cents everywhere", "inputs": ["456789.01", "2.95", "7.5", "17.5", "349.5", "1111.11", "42.5", "35"], "gross": "13475.275795", "referral": "1010.645684625", "brokerage": "2530.810269315625", "net": "8822.709841059375", "teamShare": "3749.651682450234375", "agentShare": "5073.058158609140625", "weighted": "3087.94844437078125"},
  {"name": "D14 prob 100", "inputs": ["825000", "3.5", "12.5", "22.5", "450", "975.25", "65", "100"], "gross": "28875", "referral": "3609.375", "brokerage": "6134.765625", "net": "18155.609375", "teamShare": "11801.14609375", "agentShare": "6354.46328125", "weighted": "18155.609375"},
  {"name": "D15 formatted strings ($/,/% stripped by num())", "inputs": ["425000", "3", "10", "15", "299.99", "1234.56", "50", "35"], "gross": "12750", "referral": "1275", "brokerage": "2021.24", "net": "8219.2", "teamShare": "4109.6", "agentShare": "4109.6", "weighted": "2876.72"},
  {"name": "D16 empty/null fields -> 0", "inputs": ["300000", "3", "0", "0", "0", "0", "0", "20"], "gross": "9000", "referral": "0", "brokerage": "0", "net": "9000", "teamShare": "0", "agentShare": "9000", "weighted": "1800"},
  {"name": "D17 negative price flows through, net clamps 0", "inputs": ["-250000", "6", "25", "20", "0", "500", "70", "80"], "gross": "-15000", "referral": "-3750", "brokerage": "-2250", "net": "0", "teamShare": "0", "agentShare": "0", "weighted": "0"},
  {"name": "D18 very large price 99,999,999.99", "inputs": ["99999999.99", "2.875", "5.5", "19.99", "1250.49", "9999.99", "33.33", "85"], "gross": "2874999.9997125", "referral": "158124.9999841875", "brokerage": "544353.80244568966875", "net": "2162521.20728262283125", "teamShare": "720768.318387298189655625", "agentShare": "1441752.888895324641594375", "weighted": "1838143.0261902294065625"},
  {"name": "D19 comma-decimal '3,0' parses as 30", "inputs": ["200000", "30", "0", "0", "0", "0", "0", "50"], "gross": "60000", "referral": "0", "brokerage": "0", "net": "60000", "teamShare": "0", "agentShare": "60000", "weighted": "30000"},
  {"name": "D20 heavy float chain 333333.33 @ 2.9", "inputs": ["333333.33", "2.9", "3.3", "6.7", "0.01", "0.02", "33.3", "15"], "gross": "9666.66657", "referral": "318.99999681", "brokerage": "626.30366040373", "net": "8721.34291278627", "teamShare": "2904.20718995782791", "agentShare": "5817.13572282844209", "weighted": "1308.2014369179405"},
];

// The RAW inputs actually fed to dealMath(). By default they are the oracle's
// parsed numbers; three deals instead feed the MESSY values the oracle's
// comments hand-parsed, so the num()/pct() parsing layer is inside the loop
// under test too (the oracle's "inputs" row holds the hand-parsed result).
const RAW_OVERRIDES: any = {
  "D15 formatted strings ($/,/% stripped by num())": {
    d: { price: "$425,000", commPct: "3%", referralPct: "10%", brokeragePct: "15%", brokerageFee: "$299.99", closingCosts: "$1,234.56", teamSplitPct: "50%" },
    prob: 35,
  },
  "D16 empty/null fields -> 0": {
    d: { price: 300000, commPct: 3, referralPct: "", brokeragePct: null, brokerageFee: undefined, closingCosts: "", teamSplitPct: null },
    prob: 20,
  },
  "D19 comma-decimal '3,0' parses as 30": {
    // num("3,0") strips the comma -> parseFloat("30") -> 30, NOT 3.0. This is
    // the certified (demo-identical) behavior: a European decimal comma is a
    // thousands separator to num(). Hazard noted, not judged.
    d: { price: 200000, commPct: "3,0", referralPct: 0, brokeragePct: 0, brokerageFee: 0, closingCosts: 0, teamSplitPct: 0 },
    prob: 50,
  },
};

const MONEY_KEYS = ["gross", "referral", "brokerage", "net", "teamShare", "agentShare", "weighted"];
const HALF_CENT = 0.005;

function rawFor(c: any) {
  const o = RAW_OVERRIDES[c.name];
  if (o) return o;
  const [price, commPct, referralPct, brokeragePct, brokerageFee, closingCosts, teamSplitPct, prob] = c.inputs.map(Number);
  return { d: { price, commPct, referralPct, brokeragePct, brokerageFee, closingCosts, teamSplitPct }, prob };
}

// Run all 20 up front (dealMath is pure) so the deviation summary test and
// the per-deal assertions see the same results.
const RESULTS = ORACLE.map((c: any) => {
  const { d, prob } = rawFor(c);
  const js: any = dealMath(d, { prob });
  let maxDev = 0, maxKey = null;
  for (const k of MONEY_KEYS) {
    const dev = Math.abs(js[k] - Number(c[k]));
    if (dev > maxDev) { maxDev = dev; maxKey = k; }
  }
  return { c, js, maxDev, maxKey };
});
const GLOBAL_MAX: any = RESULTS.reduce((m, r) => (r.maxDev > m.maxDev ? r : m), { maxDev: -1 });

describe('G6.7 — 20 hand-calculated deals vs Python-decimal oracle, to the cent', () => {
  for (const { c, js } of RESULTS) {
    it(`${c.name}: all 7 money outputs within half a cent of the decimal oracle`, () => {
      for (const k of MONEY_KEYS) {
        const oracle = Number((c as any)[k]);
        const dev = Math.abs((js as any)[k] - oracle);
        // Strict: half a cent. A failure here is a REAL money defect — the
        // report must name the deal, the field, and both values.
        expect(dev, `${c.name} · ${k}: JS=${(js as any)[k]} oracle=${(c as any)[k]} |Δ|=${dev}`).toBeLessThan(HALF_CENT);
      }
      // Internal consistency the oracle also guarantees: the split must
      // reconstitute the net exactly as the subtraction defines it.
      expect(js.teamShare + js.agentShare).toBeCloseTo(js.net, 8);
    });
  }

  it('max |IEEE754 - decimal| deviation across all 20×7 money values is far below half a cent (evidence)', () => {
    // Print the evidence table for the certification report.
    const lines = RESULTS.map(({ c, js, maxDev, maxKey }) =>
      `${c.name.padEnd(52)} net oracle=${c.net} js=${js.net} Δnet=${Math.abs(js.net - Number(c.net)).toExponential(4)}  weighted oracle=${c.weighted} js=${js.weighted} Δw=${Math.abs(js.weighted - Number(c.weighted)).toExponential(4)}  maxΔ(${maxKey})=${maxDev.toExponential(4)}`);
    // eslint-disable-next-line no-console
    console.log('\n[G6.7 deviation table]\n' + lines.join('\n') +
      `\n[G6.7] MAX deviation observed: ${GLOBAL_MAX.maxDev.toExponential(6)} (deal "${GLOBAL_MAX.c.name}", field ${GLOBAL_MAX.maxKey})\n`);
    expect(GLOBAL_MAX.maxDev).toBeLessThan(HALF_CENT);
  });
});

describe('G6.7 — num()/pct() input-parser behavior certification (demo-identical, lines 1480-1481)', () => {
  it('num("$425,000") -> 425000 (currency symbols and thousands commas stripped)', () => {
    expect(num('$425,000')).toBe(425000);
  });
  it('num("2.5%") -> 2.5 and pct("2.5%") -> 2.5 (trailing % stripped)', () => {
    expect(num('2.5%')).toBe(2.5);
    expect(pct('2.5%')).toBe(2.5);
  });
  it('num("") / num(null) / num(undefined) -> 0 (parseFloat NaN guard)', () => {
    expect(num('')).toBe(0);
    expect(num(null)).toBe(0);
    expect(num(undefined)).toBe(0);
  });
  it('num("3,0") -> 30 — a European decimal comma reads as a thousands separator (certified hazard, demo-identical)', () => {
    expect(num('3,0')).toBe(30);
  });
  it('num(-5) -> -5 and num("-$1,234.56") -> -1234.56 (negatives pass through num() unclamped)', () => {
    expect(num(-5)).toBe(-5);
    expect(num('-$1,234.56')).toBe(-1234.56);
  });
  it('pct() clamps only to [0,100]: pct("150%")=100, pct(-3)=0 — but num() used for price/fee/costs never clamps', () => {
    expect(pct('150%')).toBe(100);
    expect(pct(-3)).toBe(0);
    expect(num('150%')).toBe(150);
  });
});

describe('G6.7 — money() display rounding certification (src/core/fields.js:30, demo line 502)', () => {
  // money(n) = "$" + Number(n).toLocaleString(undefined, {maximumFractionDigits:0})
  // i.e. the app displays WHOLE DOLLARS, never cents. Rounding mode is
  // Intl's default "halfExpand" (half away from zero), NOT banker's.
  it('rounds to whole dollars: an unrounded net of 13900.985 displays as $13,901 (no cents shown anywhere)', () => {
    expect(money(13900.985)).toBe('$13,901');
  });
  it('a dealMath() net ending in .985 reaches display as the next whole dollar', () => {
    // price 123498.5 @ 1%: decimal-exact gross/net = 1234.985 (float stores
    // 1234.98499999999989995...). money() shows $1,235 either way: the
    // half-dollar boundary is .5, so the sub-cent float error is invisible.
    const r = dealMath({ price: 123498.5, commPct: 1 }, { prob: 100 });
    expect(Math.abs(r.net - 1234.985)).toBeLessThan(HALF_CENT);
    expect(money(r.net)).toBe('$1,235');
  });
  it('half-dollar ties round AWAY FROM ZERO (halfExpand), not banker\'s: $100.50 -> $101, $101.50 -> $102', () => {
    // Banker's (half-even) would display 100.5 as $100. Certifying actual
    // behavior: both ties round up in magnitude.
    expect(money(100.5)).toBe('$101');
    expect(money(101.5)).toBe('$102');
    expect(money(-100.5)).toBe('$-101');
  });
  it('thousands grouping matches the demo\'s documented "$425,000" shape', () => {
    expect(money(425000)).toBe('$425,000');
    expect(money(0)).toBe('$0');
  });
});
