-- supabase/seed-production.sql
-- PRODUCTION seed for a live deployment. Use this INSTEAD of seed.sql.
--
-- Contains only the configuration the app needs to run:
--   the org, the 6 roles with their 62 permission grants, lead statuses,
--   call outcomes, built-in + custom field definitions, the CRM pipelines
--   with their stages, and org settings.
--
-- Contains NO people and NO sample data:
--   no members, no logins, no teams, no leads, lists, campaigns, templates,
--   activities, follow-ups, notes, imports, deals or audit entries.
--
-- After running this nobody can sign in. The first login is created by
-- hand (see DEPLOY.md, Step 4); every later login is created inside the
-- app at Admin -> Users.
--
-- Generated from seed.sql's own config sections, so values match exactly.

begin;

-- Org
insert into orgs (id, name) values (1, 'The BG Group');

-- Roles (defaultRoles() in core/permissions.js)
insert into roles (org_id, id, name, description, built_in, super_admin) values
  (1, 'owner', 'Owner / Super Administrator', 'Complete control over the platform, including administrators, roles and system settings.', true, true),
  (1, 'manager', 'Administrator', 'Creates and manages users, assigns leads and lists, manages campaigns, CRM stages and competitions, exports data.', true, false),
  (1, 'isa_manager', 'Inside Sales Manager', 'Coaches the callers: assigns leads, reviews calls, texts and notes, monitors follow-ups and runs competitions — without system-administrator access.', true, false),
  (1, 'agent', 'Inside Sales Agent', 'Works assigned leads: calls, texts, notes, follow-ups, outcomes, moves their leads through the CRM.', true, false),
  (1, 're_agent', 'Real Estate Agent', 'Works assigned leads and their own CRM opportunities.', true, false),
  (1, 'viewer', 'Viewer / Coach', 'Reads dashboards, reports and activity. Cannot edit, delete or reassign anything.', true, false);

-- Role permissions: one row per (role, permission key) for all 62 keys
-- in the PERMISSIONS catalog (ALL_PERMS()/permsFrom() semantics).
insert into role_permissions (org_id, role_id, permission_key, allowed) values
  (1, 'owner', 'viewOwnLeads', true),
  (1, 'owner', 'viewTeamLeads', true),
  (1, 'owner', 'viewAllLeads', true),
  (1, 'owner', 'createLeads', true),
  (1, 'owner', 'editLeads', true),
  (1, 'owner', 'deleteLeads', true),
  (1, 'owner', 'assignLeads', true),
  (1, 'owner', 'reassign', true),
  (1, 'owner', 'export', true),
  (1, 'owner', 'import', true),
  (1, 'owner', 'manageLists', true),
  (1, 'owner', 'editDnc', true),
  (1, 'owner', 'makeCalls', true),
  (1, 'owner', 'sendTexts', true),
  (1, 'owner', 'addNotes', true),
  (1, 'owner', 'createFollowUps', true),
  (1, 'owner', 'editOutcomes', true),
  (1, 'owner', 'viewAttempts', true),
  (1, 'owner', 'browserDialer', true),
  (1, 'owner', 'viewPhones', true),
  (1, 'owner', 'markSent', true),
  (1, 'owner', 'managerNotes', true),
  (1, 'owner', 'viewOwnPipeline', true),
  (1, 'owner', 'viewTeamPipeline', true),
  (1, 'owner', 'viewAllPipelines', true),
  (1, 'owner', 'moveStages', true),
  (1, 'owner', 'manageCrm', true),
  (1, 'owner', 'viewPrices', true),
  (1, 'owner', 'viewCommissions', true),
  (1, 'owner', 'editDealFinancials', true),
  (1, 'owner', 'exportCrm', true),
  (1, 'owner', 'manageCampaigns', true),
  (1, 'owner', 'editCampaigns', true),
  (1, 'owner', 'deleteCampaigns', true),
  (1, 'owner', 'assignCampaigns', true),
  (1, 'owner', 'createTemplates', true),
  (1, 'owner', 'creativeMessages', true),
  (1, 'owner', 'viewTeamMembers', true),
  (1, 'owner', 'createTeams', true),
  (1, 'owner', 'editTeams', true),
  (1, 'owner', 'assignMembers', true),
  (1, 'owner', 'assignManagers', true),
  (1, 'owner', 'viewTeamReports', true),
  (1, 'owner', 'viewCompetitions', true),
  (1, 'owner', 'participate', true),
  (1, 'owner', 'createCompetitions', true),
  (1, 'owner', 'editCompetitions', true),
  (1, 'owner', 'manageScoring', true),
  (1, 'owner', 'viewAllResults', true),
  (1, 'owner', 'createUsers', true),
  (1, 'owner', 'editUsers', true),
  (1, 'owner', 'deactivateUsers', true),
  (1, 'owner', 'resetPasswords', true),
  (1, 'owner', 'createRoles', true),
  (1, 'owner', 'editPermissions', true),
  (1, 'owner', 'manageIntegrations', true),
  (1, 'owner', 'viewAudit', true),
  (1, 'owner', 'exportReports', true),
  (1, 'owner', 'manageSettings', true),
  (1, 'owner', 'manageOutcomes', true),
  (1, 'owner', 'manageFields', true),
  (1, 'owner', 'manageStatuses', true),
  (1, 'manager', 'viewOwnLeads', true),
  (1, 'manager', 'viewTeamLeads', true),
  (1, 'manager', 'viewAllLeads', true),
  (1, 'manager', 'createLeads', true),
  (1, 'manager', 'editLeads', true),
  (1, 'manager', 'deleteLeads', true),
  (1, 'manager', 'assignLeads', true),
  (1, 'manager', 'reassign', true),
  (1, 'manager', 'export', true),
  (1, 'manager', 'import', true),
  (1, 'manager', 'manageLists', true),
  (1, 'manager', 'editDnc', true),
  (1, 'manager', 'makeCalls', true),
  (1, 'manager', 'sendTexts', true),
  (1, 'manager', 'addNotes', true),
  (1, 'manager', 'createFollowUps', true),
  (1, 'manager', 'editOutcomes', true),
  (1, 'manager', 'viewAttempts', true),
  (1, 'manager', 'browserDialer', true),
  (1, 'manager', 'viewPhones', true),
  (1, 'manager', 'markSent', true),
  (1, 'manager', 'managerNotes', true),
  (1, 'manager', 'viewOwnPipeline', true),
  (1, 'manager', 'viewTeamPipeline', true),
  (1, 'manager', 'viewAllPipelines', true),
  (1, 'manager', 'moveStages', true),
  (1, 'manager', 'manageCrm', true),
  (1, 'manager', 'viewPrices', true),
  (1, 'manager', 'viewCommissions', true),
  (1, 'manager', 'editDealFinancials', true),
  (1, 'manager', 'exportCrm', true),
  (1, 'manager', 'manageCampaigns', true),
  (1, 'manager', 'editCampaigns', true),
  (1, 'manager', 'deleteCampaigns', true),
  (1, 'manager', 'assignCampaigns', true),
  (1, 'manager', 'createTemplates', true),
  (1, 'manager', 'creativeMessages', true),
  (1, 'manager', 'viewTeamMembers', true),
  (1, 'manager', 'createTeams', true),
  (1, 'manager', 'editTeams', true),
  (1, 'manager', 'assignMembers', true),
  (1, 'manager', 'assignManagers', true),
  (1, 'manager', 'viewTeamReports', true),
  (1, 'manager', 'viewCompetitions', true),
  (1, 'manager', 'participate', true),
  (1, 'manager', 'createCompetitions', true),
  (1, 'manager', 'editCompetitions', true),
  (1, 'manager', 'manageScoring', true),
  (1, 'manager', 'viewAllResults', true),
  (1, 'manager', 'createUsers', true),
  (1, 'manager', 'editUsers', true),
  (1, 'manager', 'deactivateUsers', true),
  (1, 'manager', 'resetPasswords', true),
  (1, 'manager', 'createRoles', false),
  (1, 'manager', 'editPermissions', false),
  (1, 'manager', 'manageIntegrations', false),
  (1, 'manager', 'viewAudit', true),
  (1, 'manager', 'exportReports', true),
  (1, 'manager', 'manageSettings', true),
  (1, 'manager', 'manageOutcomes', true),
  (1, 'manager', 'manageFields', true),
  (1, 'manager', 'manageStatuses', true),
  (1, 'isa_manager', 'viewOwnLeads', true),
  (1, 'isa_manager', 'viewTeamLeads', true),
  (1, 'isa_manager', 'viewAllLeads', false),
  (1, 'isa_manager', 'createLeads', true),
  (1, 'isa_manager', 'editLeads', true),
  (1, 'isa_manager', 'deleteLeads', false),
  (1, 'isa_manager', 'assignLeads', true),
  (1, 'isa_manager', 'reassign', true),
  (1, 'isa_manager', 'export', true),
  (1, 'isa_manager', 'import', true),
  (1, 'isa_manager', 'manageLists', true),
  (1, 'isa_manager', 'editDnc', true),
  (1, 'isa_manager', 'makeCalls', true),
  (1, 'isa_manager', 'sendTexts', true),
  (1, 'isa_manager', 'addNotes', true),
  (1, 'isa_manager', 'createFollowUps', true),
  (1, 'isa_manager', 'editOutcomes', true),
  (1, 'isa_manager', 'viewAttempts', true),
  (1, 'isa_manager', 'browserDialer', true),
  (1, 'isa_manager', 'viewPhones', true),
  (1, 'isa_manager', 'markSent', true),
  (1, 'isa_manager', 'managerNotes', true),
  (1, 'isa_manager', 'viewOwnPipeline', true),
  (1, 'isa_manager', 'viewTeamPipeline', true),
  (1, 'isa_manager', 'viewAllPipelines', false),
  (1, 'isa_manager', 'moveStages', true),
  (1, 'isa_manager', 'manageCrm', false),
  (1, 'isa_manager', 'viewPrices', true),
  (1, 'isa_manager', 'viewCommissions', true),
  (1, 'isa_manager', 'editDealFinancials', true),
  (1, 'isa_manager', 'exportCrm', true),
  (1, 'isa_manager', 'manageCampaigns', true),
  (1, 'isa_manager', 'editCampaigns', true),
  (1, 'isa_manager', 'deleteCampaigns', false),
  (1, 'isa_manager', 'assignCampaigns', true),
  (1, 'isa_manager', 'createTemplates', true),
  (1, 'isa_manager', 'creativeMessages', true),
  (1, 'isa_manager', 'viewTeamMembers', true),
  (1, 'isa_manager', 'createTeams', false),
  (1, 'isa_manager', 'editTeams', false),
  (1, 'isa_manager', 'assignMembers', true),
  (1, 'isa_manager', 'assignManagers', false),
  (1, 'isa_manager', 'viewTeamReports', true),
  (1, 'isa_manager', 'viewCompetitions', true),
  (1, 'isa_manager', 'participate', true),
  (1, 'isa_manager', 'createCompetitions', true),
  (1, 'isa_manager', 'editCompetitions', true),
  (1, 'isa_manager', 'manageScoring', true),
  (1, 'isa_manager', 'viewAllResults', true),
  (1, 'isa_manager', 'createUsers', false),
  (1, 'isa_manager', 'editUsers', false),
  (1, 'isa_manager', 'deactivateUsers', false),
  (1, 'isa_manager', 'resetPasswords', false),
  (1, 'isa_manager', 'createRoles', false),
  (1, 'isa_manager', 'editPermissions', false),
  (1, 'isa_manager', 'manageIntegrations', false),
  (1, 'isa_manager', 'viewAudit', false),
  (1, 'isa_manager', 'exportReports', true),
  (1, 'isa_manager', 'manageSettings', false),
  (1, 'isa_manager', 'manageOutcomes', false),
  (1, 'isa_manager', 'manageFields', false),
  (1, 'isa_manager', 'manageStatuses', false),
  (1, 'agent', 'viewOwnLeads', true),
  (1, 'agent', 'viewTeamLeads', false),
  (1, 'agent', 'viewAllLeads', false),
  (1, 'agent', 'createLeads', true),
  (1, 'agent', 'editLeads', true),
  (1, 'agent', 'deleteLeads', false),
  (1, 'agent', 'assignLeads', false),
  (1, 'agent', 'reassign', false),
  (1, 'agent', 'export', true),
  (1, 'agent', 'import', false),
  (1, 'agent', 'manageLists', false),
  (1, 'agent', 'editDnc', false),
  (1, 'agent', 'makeCalls', true),
  (1, 'agent', 'sendTexts', true),
  (1, 'agent', 'addNotes', true),
  (1, 'agent', 'createFollowUps', true),
  (1, 'agent', 'editOutcomes', true),
  (1, 'agent', 'viewAttempts', true),
  (1, 'agent', 'browserDialer', true),
  (1, 'agent', 'viewPhones', true),
  (1, 'agent', 'markSent', true),
  (1, 'agent', 'managerNotes', false),
  (1, 'agent', 'viewOwnPipeline', true),
  (1, 'agent', 'viewTeamPipeline', false),
  (1, 'agent', 'viewAllPipelines', false),
  (1, 'agent', 'moveStages', true),
  (1, 'agent', 'manageCrm', false),
  (1, 'agent', 'viewPrices', true),
  (1, 'agent', 'viewCommissions', false),
  (1, 'agent', 'editDealFinancials', false),
  (1, 'agent', 'exportCrm', false),
  (1, 'agent', 'manageCampaigns', false),
  (1, 'agent', 'editCampaigns', false),
  (1, 'agent', 'deleteCampaigns', false),
  (1, 'agent', 'assignCampaigns', false),
  (1, 'agent', 'createTemplates', false),
  (1, 'agent', 'creativeMessages', false),
  (1, 'agent', 'viewTeamMembers', true),
  (1, 'agent', 'createTeams', false),
  (1, 'agent', 'editTeams', false),
  (1, 'agent', 'assignMembers', false),
  (1, 'agent', 'assignManagers', false),
  (1, 'agent', 'viewTeamReports', false),
  (1, 'agent', 'viewCompetitions', true),
  (1, 'agent', 'participate', true),
  (1, 'agent', 'createCompetitions', false),
  (1, 'agent', 'editCompetitions', false),
  (1, 'agent', 'manageScoring', false),
  (1, 'agent', 'viewAllResults', false),
  (1, 'agent', 'createUsers', false),
  (1, 'agent', 'editUsers', false),
  (1, 'agent', 'deactivateUsers', false),
  (1, 'agent', 'resetPasswords', false),
  (1, 'agent', 'createRoles', false),
  (1, 'agent', 'editPermissions', false),
  (1, 'agent', 'manageIntegrations', false),
  (1, 'agent', 'viewAudit', false),
  (1, 'agent', 'exportReports', false),
  (1, 'agent', 'manageSettings', false),
  (1, 'agent', 'manageOutcomes', false),
  (1, 'agent', 'manageFields', false),
  (1, 'agent', 'manageStatuses', false),
  (1, 're_agent', 'viewOwnLeads', true),
  (1, 're_agent', 'viewTeamLeads', false),
  (1, 're_agent', 'viewAllLeads', false),
  (1, 're_agent', 'createLeads', true),
  (1, 're_agent', 'editLeads', true),
  (1, 're_agent', 'deleteLeads', false),
  (1, 're_agent', 'assignLeads', false),
  (1, 're_agent', 'reassign', false),
  (1, 're_agent', 'export', true),
  (1, 're_agent', 'import', false),
  (1, 're_agent', 'manageLists', false),
  (1, 're_agent', 'editDnc', false),
  (1, 're_agent', 'makeCalls', true),
  (1, 're_agent', 'sendTexts', true),
  (1, 're_agent', 'addNotes', true),
  (1, 're_agent', 'createFollowUps', true),
  (1, 're_agent', 'editOutcomes', true),
  (1, 're_agent', 'viewAttempts', true),
  (1, 're_agent', 'browserDialer', true),
  (1, 're_agent', 'viewPhones', true),
  (1, 're_agent', 'markSent', true),
  (1, 're_agent', 'managerNotes', false),
  (1, 're_agent', 'viewOwnPipeline', true),
  (1, 're_agent', 'viewTeamPipeline', false),
  (1, 're_agent', 'viewAllPipelines', false),
  (1, 're_agent', 'moveStages', true),
  (1, 're_agent', 'manageCrm', false),
  (1, 're_agent', 'viewPrices', true),
  (1, 're_agent', 'viewCommissions', true),
  (1, 're_agent', 'editDealFinancials', false),
  (1, 're_agent', 'exportCrm', false),
  (1, 're_agent', 'manageCampaigns', false),
  (1, 're_agent', 'editCampaigns', false),
  (1, 're_agent', 'deleteCampaigns', false),
  (1, 're_agent', 'assignCampaigns', false),
  (1, 're_agent', 'createTemplates', false),
  (1, 're_agent', 'creativeMessages', false),
  (1, 're_agent', 'viewTeamMembers', true),
  (1, 're_agent', 'createTeams', false),
  (1, 're_agent', 'editTeams', false),
  (1, 're_agent', 'assignMembers', false),
  (1, 're_agent', 'assignManagers', false),
  (1, 're_agent', 'viewTeamReports', false),
  (1, 're_agent', 'viewCompetitions', true),
  (1, 're_agent', 'participate', true),
  (1, 're_agent', 'createCompetitions', false),
  (1, 're_agent', 'editCompetitions', false),
  (1, 're_agent', 'manageScoring', false),
  (1, 're_agent', 'viewAllResults', false),
  (1, 're_agent', 'createUsers', false),
  (1, 're_agent', 'editUsers', false),
  (1, 're_agent', 'deactivateUsers', false),
  (1, 're_agent', 'resetPasswords', false),
  (1, 're_agent', 'createRoles', false),
  (1, 're_agent', 'editPermissions', false),
  (1, 're_agent', 'manageIntegrations', false),
  (1, 're_agent', 'viewAudit', false),
  (1, 're_agent', 'exportReports', false),
  (1, 're_agent', 'manageSettings', false),
  (1, 're_agent', 'manageOutcomes', false),
  (1, 're_agent', 'manageFields', false),
  (1, 're_agent', 'manageStatuses', false),
  (1, 'viewer', 'viewOwnLeads', true),
  (1, 'viewer', 'viewTeamLeads', true),
  (1, 'viewer', 'viewAllLeads', false),
  (1, 'viewer', 'createLeads', false),
  (1, 'viewer', 'editLeads', false),
  (1, 'viewer', 'deleteLeads', false),
  (1, 'viewer', 'assignLeads', false),
  (1, 'viewer', 'reassign', false),
  (1, 'viewer', 'export', false),
  (1, 'viewer', 'import', false),
  (1, 'viewer', 'manageLists', false),
  (1, 'viewer', 'editDnc', false),
  (1, 'viewer', 'makeCalls', false),
  (1, 'viewer', 'sendTexts', false),
  (1, 'viewer', 'addNotes', false),
  (1, 'viewer', 'createFollowUps', false),
  (1, 'viewer', 'editOutcomes', false),
  (1, 'viewer', 'viewAttempts', true),
  (1, 'viewer', 'browserDialer', false),
  (1, 'viewer', 'viewPhones', false),
  (1, 'viewer', 'markSent', false),
  (1, 'viewer', 'managerNotes', false),
  (1, 'viewer', 'viewOwnPipeline', true),
  (1, 'viewer', 'viewTeamPipeline', true),
  (1, 'viewer', 'viewAllPipelines', false),
  (1, 'viewer', 'moveStages', false),
  (1, 'viewer', 'manageCrm', false),
  (1, 'viewer', 'viewPrices', true),
  (1, 'viewer', 'viewCommissions', false),
  (1, 'viewer', 'editDealFinancials', false),
  (1, 'viewer', 'exportCrm', false),
  (1, 'viewer', 'manageCampaigns', false),
  (1, 'viewer', 'editCampaigns', false),
  (1, 'viewer', 'deleteCampaigns', false),
  (1, 'viewer', 'assignCampaigns', false),
  (1, 'viewer', 'createTemplates', false),
  (1, 'viewer', 'creativeMessages', false),
  (1, 'viewer', 'viewTeamMembers', true),
  (1, 'viewer', 'createTeams', false),
  (1, 'viewer', 'editTeams', false),
  (1, 'viewer', 'assignMembers', false),
  (1, 'viewer', 'assignManagers', false),
  (1, 'viewer', 'viewTeamReports', true),
  (1, 'viewer', 'viewCompetitions', true),
  (1, 'viewer', 'participate', false),
  (1, 'viewer', 'createCompetitions', false),
  (1, 'viewer', 'editCompetitions', false),
  (1, 'viewer', 'manageScoring', false),
  (1, 'viewer', 'viewAllResults', true),
  (1, 'viewer', 'createUsers', false),
  (1, 'viewer', 'editUsers', false),
  (1, 'viewer', 'deactivateUsers', false),
  (1, 'viewer', 'resetPasswords', false),
  (1, 'viewer', 'createRoles', false),
  (1, 'viewer', 'editPermissions', false),
  (1, 'viewer', 'manageIntegrations', false),
  (1, 'viewer', 'viewAudit', false),
  (1, 'viewer', 'exportReports', false),
  (1, 'viewer', 'manageSettings', false),
  (1, 'viewer', 'manageOutcomes', false),
  (1, 'viewer', 'manageFields', false),
  (1, 'viewer', 'manageStatuses', false);

-- Statuses (defaultStatuses())
insert into statuses (org_id, key, label, tone, active, locked, "order") values
  (1, 'new', 'New', 'blue', true, true, 0),
  (1, 'attempted', 'Attempted', '', true, true, 10),
  (1, 'contacted', 'Contacted', 'green', true, true, 20),
  (1, 'appointment', 'Appointment', 'green', true, true, 30),
  (1, 'do_not_call', 'Do Not Call', 'red', true, true, 40),
  (1, 'do_not_contact', 'Do Not Contact', 'red', true, true, 50),
  (1, 'closed', 'Closed', '', true, false, 60);

-- Outcomes
insert into outcomes (id, org_id, name, conv, appt, dnc, disabled) values
  (1, 1, 'No answer', false, false, false, false),
  (2, 1, 'Left voicemail', false, false, false, false),
  (3, 1, 'Wrong number', false, false, false, false),
  (4, 1, 'Not interested', true, false, false, false),
  (5, 1, 'Interested', true, false, false, false),
  (6, 1, 'Appointment set', true, true, false, false),
  (7, 1, 'Call back later', true, false, false, false),
  (8, 1, 'Do not call', false, false, true, false);

-- Built-in fields (defaultBuiltInFields())
insert into built_in_fields (org_id, key, label, visible, required, always) values
  (1, 'first', 'First name', true, false, true),
  (1, 'last', 'Last name', true, false, true),
  (1, 'phone', 'Phone', true, false, true),
  (1, 'email', 'Email', true, false, false),
  (1, 'addr', 'Street address', true, false, false),
  (1, 'city', 'City', true, false, false),
  (1, 'state', 'State', false, false, false),
  (1, 'zip', 'ZIP', true, false, false);

-- Custom fields
insert into custom_fields (id, org_id, key, label, type, choices, hint, in_table, on_card, active, "order") values
  (1, 1, 'listing_price', 'Listing price', 'money', '[]'::jsonb, 'What it was last listed at.', true, true, true, 10),
  (2, 1, 'expired_on', 'Expired on', 'date', '[]'::jsonb, '', false, true, true, 20),
  (3, 1, 'motivation', 'Motivation', 'choice', '["Hot", "Warm", "Cold"]'::jsonb, 'How ready they sound.', true, false, true, 30),
  (4, 1, 'vacant', 'Vacant', 'yes_no', '[]'::jsonb, '', false, false, true, 40);

-- Pipelines (newPipeline() x2, each with defaultStages()'s 14 stages)
insert into pipelines (id, org_id, name, kind, archived, created_at) values
  (1071, 1, 'Seller Leads', 'seller', false, '2026-09-29T20:27:51.074Z'),
  (1086, 1, 'Probate', 'probate', false, '2026-09-29T20:27:51.074Z');

insert into stages (id, org_id, pipeline_id, name, prob, kind, color, archived, "position") values
  (1072, 1, 1071, 'New Lead', 5, 'active', '#8E8E93', false, 0),
  (1073, 1, 1071, 'Attempting Contact', 10, 'active', '#8E8E93', false, 1),
  (1074, 1, 1071, 'Contact Made', 15, 'active', '#0A84FF', false, 2),
  (1075, 1, 1071, 'Follow-Up', 20, 'active', '#0A84FF', false, 3),
  (1076, 1, 1071, 'Appointment Scheduled', 35, 'active', '#5E5CE6', false, 4),
  (1077, 1, 1071, 'Appointment Completed', 45, 'active', '#5E5CE6', false, 5),
  (1078, 1, 1071, 'Potential Client', 55, 'active', '#BF5AF2', false, 6),
  (1079, 1, 1071, 'Listing Agreement Sent', 65, 'active', '#FF9F0A', false, 7),
  (1080, 1, 1071, 'Listing Signed', 80, 'active', '#FF9F0A', false, 8),
  (1081, 1, 1071, 'Active Listing', 85, 'active', '#30D158', false, 9),
  (1082, 1, 1071, 'Under Contract', 95, 'active', '#30D158', false, 10),
  (1083, 1, 1071, 'Closed', 100, 'closed', '#30D158', false, 11),
  (1084, 1, 1071, 'Long-Term Nurture', 5, 'active', '#64D2FF', false, 12),
  (1085, 1, 1071, 'Lost Lead', 0, 'lost', '#FF453A', false, 13),
  (1087, 1, 1086, 'New Lead', 5, 'active', '#8E8E93', false, 0),
  (1088, 1, 1086, 'Attempting Contact', 10, 'active', '#8E8E93', false, 1),
  (1089, 1, 1086, 'Contact Made', 15, 'active', '#0A84FF', false, 2),
  (1090, 1, 1086, 'Follow-Up', 20, 'active', '#0A84FF', false, 3),
  (1091, 1, 1086, 'Appointment Scheduled', 35, 'active', '#5E5CE6', false, 4),
  (1092, 1, 1086, 'Appointment Completed', 45, 'active', '#5E5CE6', false, 5),
  (1093, 1, 1086, 'Potential Client', 55, 'active', '#BF5AF2', false, 6),
  (1094, 1, 1086, 'Listing Agreement Sent', 65, 'active', '#FF9F0A', false, 7),
  (1095, 1, 1086, 'Listing Signed', 80, 'active', '#FF9F0A', false, 8),
  (1096, 1, 1086, 'Active Listing', 85, 'active', '#30D158', false, 9),
  (1097, 1, 1086, 'Under Contract', 95, 'active', '#30D158', false, 10),
  (1098, 1, 1086, 'Closed', 100, 'closed', '#30D158', false, 11),
  (1099, 1, 1086, 'Long-Term Nurture', 5, 'active', '#64D2FF', false, 12),
  (1100, 1, 1086, 'Lost Lead', 0, 'lost', '#FF453A', false, 13);

-- Org settings
insert into org_settings (org_id, team_name, agent_name, table_columns, card_fields, pts_call, pts_text, pts_door, pts_conv, pts_appt, weekly_goal, working_days, import_cfg) values
  (1, 'The BG Group', 'Travon', '[]'::jsonb, '[]'::jsonb, 1, 1, 2, 5, 25, 250, '[1, 2, 3, 4, 5]'::jsonb, '{"phoneSlots": 10, "emailSlots": 1, "dupPhone": true, "dupEmail": true, "dupAddress": true, "maxRows": 50000, "requireName": false, "requirePhone": false, "flagDnc": true, "defaultAssign": "", "defaultList": ""}'::jsonb);

-- Start every id sequence just past the seeded config rows.
select setval(pg_get_serial_sequence('orgs', 'id'), coalesce((select max(id) from orgs), 0) + 1, false);
select setval(pg_get_serial_sequence('outcomes', 'id'), coalesce((select max(id) from outcomes), 0) + 1, false);
select setval(pg_get_serial_sequence('custom_fields', 'id'), coalesce((select max(id) from custom_fields), 0) + 1, false);
select setval(pg_get_serial_sequence('pipelines', 'id'), coalesce((select max(id) from pipelines), 0) + 1, false);
select setval(pg_get_serial_sequence('stages', 'id'), coalesce((select max(id) from stages), 0) + 1, false);

commit;
